-- MySQL Script generated by MySQL Workbench
-- Fri Jul 28 11:45:50 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Modas_
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Modas_
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Modas_` DEFAULT CHARACTER SET utf8 ;
USE `Modas_` ;

-- -----------------------------------------------------
-- Table `Modas_`.`Diseñador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Modas_`.`Diseñador` (
  `Iddiseñador` INT NOT NULL AUTO_INCREMENT,
  `Nombre_completo` VARCHAR(45) NOT NULL,
  `Correo` VARCHAR(45) NOT NULL,
  `Contraseña` VARCHAR(45) NOT NULL,
  `Fecha_publicacion` DATE NOT NULL,
  `Identificacion` INT NOT NULL,
  `Telefono` INT NOT NULL,
  `Precio` DECIMAL NOT NULL,
  PRIMARY KEY (`Iddiseñador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Modas_`.`Comprador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Modas_`.`Comprador` (
  `Idcomprador` INT NOT NULL AUTO_INCREMENT,
  `Nombre_completo` VARCHAR(45) NOT NULL,
  `Correo` VARCHAR(45) NOT NULL,
  `Contraseña` VARCHAR(45) NOT NULL,
  `Fecha_nacimiento` DATE NOT NULL,
  `Telefono` INT NOT NULL,
  `Identificacion` INT NOT NULL,
  `Direccion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Idcomprador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Modas_`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Modas_`.`Categoria` (
  `Idcategoria` INT NOT NULL AUTO_INCREMENT,
  `Nombre_Completo` VARCHAR(45) NOT NULL,
  `Correo` VARCHAR(45) NOT NULL,
  `Contraseña` VARCHAR(45) NOT NULL,
  `Identificacion` INT NOT NULL,
  `Tipo_usuario` VARCHAR(45) NOT NULL,
  `Tipo_diseño` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Idcategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Modas_`.`Coleccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Modas_`.`Coleccion` (
  `Idcoleccion` INT NOT NULL AUTO_INCREMENT,
  `Nombre_completo` VARCHAR(45) NOT NULL,
  `Correo` VARCHAR(45) NOT NULL,
  `Contraseña` VARCHAR(45) NOT NULL,
  `Tipo_usuario` VARCHAR(45) NOT NULL,
  `Telfono` INT NOT NULL,
  `Identificacion` INT NOT NULL,
  PRIMARY KEY (`Idcoleccion`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
